apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb2
  template:
    metadata:
      labels:
        app: influxdb2
    spec:
      containers:
        - name: influxdb2
          image: influxdb:2.7
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb2-storage
              mountPath: /var/lib/influxdb2
      volumes:
        - name: influxdb2-storage
          persistentVolumeClaim:
            claimName: influxdb2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb2
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: influxdb2
